In [1]:
import numpy as np

In [2]:
# Creating a numpy array
x = np.array([1,2,3,4])
print("Numpy array :",x)
print("Type :",type(x))

Numpy array : [1 2 3 4]
Type : <class 'numpy.ndarray'>


In [7]:
# Creating a list
x = [1,2,3,4]
print("Normal list:",x)
print("Type :",type(x))

Normal list: [1, 2, 3, 4]
Type : <class 'list'>


# Time for creating a list and a numpy array

In [14]:
%timeit [j**4 for j in range(1,1000)]

174 μs ± 15.3 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [16]:
%timeit np.arange(1,1000)**4

7.88 μs ± 266 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [32]:
# Taking input from user and creating an array
l = []
for i in range(1,6):
    x = int(input("Please enter an integer : "))
    l.append(x)
print("The list of integers you entered is :",l)
print("Type :",type(l))
print("Converting to an array...")
x = np.array(l)
print("Array created :",x)
print("Type :",type(x))
print("Dimensions : ",x.ndim) # Ndim is used to find the dimensions of  numpy array

Please enter an integer :  1
Please enter an integer :  2
Please enter an integer :  3
Please enter an integer :  4
Please enter an integer :  4


The list of integers you entered is : [1, 2, 3, 4, 4]
Type : <class 'list'>
Converting to an array...
Array created : [1 2 3 4 4]
Type : <class 'numpy.ndarray'>
Dimensions :  1


In [52]:
# 2 dimensional array:
ar2 = np.array([[1,2,3],[4,5,6]]) # Number of entries or elements must be same of the inner lists
print(ar2)
print("Type :",type(ar2))
print("Dimensions : ",ar2.ndim)

[[1 2 3]
 [4 5 6]]
Type : <class 'numpy.ndarray'>
Dimensions :  2


In [64]:
# 3 dimensional array:
ar3 = np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]]) # Number of entries or elements must be same of the inner lists
print(ar3)
print("Type :",type(ar3))
print("Dimensions : ",ar3.ndim)
# In similar way we can make n dimensional arrays

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
Type : <class 'numpy.ndarray'>
Dimensions :  3


In [68]:
# n dimensional array
arn = np.array([1,2,3,4], ndmin = 10)
print(arn)
print("Type :",type(arn))
print("Dimensions : ",arn.ndim)

[[[[[[[[[[1 2 3 4]]]]]]]]]]
Type : <class 'numpy.ndarray'>
Dimensions :  10
