In [1]:
import numpy as np

# zeros()

In [3]:
# Creating 1 dimensional array with all elements 0
zeros = np.zeros(4)
print(zeros)

[0. 0. 0. 0.]


In [5]:
# Creating 2 dimensional array with all elements 0
zeros1 = np.zeros((3,4)) # With 3 rows and 4 columns
print(zeros1)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


# ones()

In [9]:
# Creating 1 dimensional array with all elements 1
ar_one = np.ones(4)
print(ar_one)

[1. 1. 1. 1.]


In [11]:
# Creating 1 dimensional array with all elements 1
ar_one = np.ones((3,4))
print(ar_one)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


# Creating an empty array

In [16]:
emp_array = np.empty(4)
print("Empty array with vacany of 4 elements : ",emp_array) 
# you will see that there are 1s in array it is because previous values are assigned to empty array

Empty array with vacany of 4 elements :  [1. 1. 1. 1.]


# Creating an array with range of elements with arrange()

In [22]:
range_array = np.arange(4)
print(range_array)

[0 1 2 3]


In [26]:
range_array = np.arange(0,11,2)
print(range_array)

[ 0  2  4  6  8 10]


# Array with diagonal elements = 1 with eye()

In [32]:
diag_array = np.eye(3)
print(diag_array)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [34]:
diag_array = np.eye(3,5) # 3x5 matrix with diagonal elemnets = 1
print(diag_array)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]


# Array with values that are spaced linearly in a specified interval

In [55]:
line_array = np.linspace(0,10, num = 5)
print(line_array)

[ 0.   2.5  5.   7.5 10. ]
