# Creating numpy array with random numbers

In [2]:
import numpy as np

In [10]:
# rand(): is used to generate random values between 1 and 0
# randn(): is used to generate random numbers close to 0 they may be positive or negative
# ranf(): is used for doing random sampling in numpy . it returns an array of specified shape 
#         and fills it with floats in the half open interval [0.0, 1.0)
# randint(): is ussed to generate random numbers between a given range

# rand()

In [25]:
# rand(): is used to generate random values between 1 and 0
var = np.random.rand(10) # as rand() is function of random module
print(var)


[0.78523066 0.01168012 0.05972767 0.88205347 0.27761859 0.06490636
 0.96071435 0.40943912 0.93277663 0.06791773]


In [18]:
var1 = np.random.rand(2,5) # 2d array with 2 rows and 5 columns
print(var1)

[[0.56928377 0.53233113 0.98330465 0.47111119 0.82401753]
 [0.51864566 0.66978952 0.09422052 0.00868025 0.40546207]]


# randn()

In [23]:
# randn(): is used to generate random numbers close to 0 they may be positive or negative
var3 = np.random.randn(10)
print(var3)

[ 1.2596067  -1.30777573  0.50802013 -1.26521872  0.31550602 -1.90137395
  0.68768352 -0.00404072  0.04896471 -1.13464359]


# randf()

In [30]:
# ranf(): is used for doing random sampling in numpy . it returns an array of specified shape 
#         and fills it with floats in the half open interval [0.0, 1.0) 1 is not included while 0 is included

var4  = np.random.rand(10)
print(var4)

[0.53458918 0.80886975 0.66137676 0.45703211 0.67386803 0.24489155
 0.17125522 0.00776489 0.54502212 0.23827312]


# randint()

In [37]:
# randint(): is ussed to generate random numbers between a given range
var5 = np.random.randint(5,20,10) # randint(min, max, total_numbers)
print(var5)

[13 16 10 14 14 10  6  7  6  9]
