# Numpy data types

In [3]:
import numpy as np

In [7]:
var = np.array([1,2,3,4])
print("Data type:",var.dtype)

Data type: int32


In [9]:
var = np.array([1.0,2.23,3.2343,4.13123])
print("Data type:",var.dtype)

Data type: float64


In [11]:
var = np.array(["a", "s", "d", "f"])
print("Data type:",var.dtype)

Data type: <U1


In [13]:
var = np.array(["a", "s", "d", 1, 2, 3])
print("Data type:",var.dtype)

Data type: <U11


In [23]:
# Changing data type
x = np.array([1,2,3,4])
print("Data type:",x.dtype)

x = np.array([1,2,3,4], dtype = np.int8)
print("Data type:",x.dtype)

# Shortcut 
x = np.array([1,2,3,4], dtype = "f")
print("Data type:",x.dtype)


Data type: int32
Data type: int8
Data type: float32


In [29]:
# Using as a function
x1 = np.array([1,2,3,4])
new  = np.float32(x1)

print("Data type:",x1.dtype)
print("Data type:",new.dtype)

print(x1)
print(new)

Data type: int32
Data type: float32
[1 2 3 4]
[1. 2. 3. 4.]


In [33]:
# Using as a function
x1 = np.array([1,2,3,4])
new  = np.float32(x1)
new1 = np.int_(new)

print("Data type:",x1.dtype)
print("Data type:",new.dtype)
print("Data type:",new1.dtype)

print(x1)
print(new)
print(new1)


Data type: int32
Data type: float32
Data type: int32
[1 2 3 4]
[1. 2. 3. 4.]
[1 2 3 4]


In [35]:
# Directly changing type
x3 = np.array([1,2,3,4])
new2 = x3.astype(float)
print(x3)
print(new2)

[1 2 3 4]
[1. 2. 3. 4.]
