# Arithmetic Operations in NumPy

In [3]:
import numpy as np

In [25]:
# By using arithmetic operators
var = np.array([1,2,3,4])
var_add = var + 3
print(var)
print(var_add)

[1 2 3 4]
[4 5 6 7]


In [27]:
# By using numpy function
var = np.array([1,2,3,4])
var_add = np.add(var, 3)
print(var)
print(var_add)

[1 2 3 4]
[4 5 6 7]


In [29]:
# By using arithmetic operators
var1 = np.array([1,2,3,4])
var2 = np.array([1,2,3,4])
var_add = var1 + var2
var_sub = var1 - var2
var_mul = var1 * var2
var_div = var1 / var2
var_pow = var1 ** var2
var_mod = var1 % var2
var_reciprocal = 1 / var1
print(var1,"+",var2,"=",var_add)
print(var1,"-",var2,"=",var_sub)
print(var1,"*",var2,"=",var_mul)
print(var1,"/",var2,"=",var_div)
print(var1,"**",var2,"=",var_pow)
print(var1,"%",var2,"=",var_mod)
print(1,"/",var1,"=",var_reciprocal)



[1 2 3 4] + [1 2 3 4] = [2 4 6 8]
[1 2 3 4] - [1 2 3 4] = [0 0 0 0]
[1 2 3 4] * [1 2 3 4] = [ 1  4  9 16]
[1 2 3 4] / [1 2 3 4] = [1. 1. 1. 1.]
[1 2 3 4] ** [1 2 3 4] = [  1   4  27 256]
[1 2 3 4] % [1 2 3 4] = [0 0 0 0]
1 / [1 2 3 4] = [1.         0.5        0.33333333 0.25      ]


In [31]:
# By using numpy functions
var1 = np.array([1,2,3,4])
var2 = np.array([1,2,3,4])
var_add = np.add(var1, var2)
var_sub = np.subtract(var1, var2)
var_mul = np.multiply(var1, var2)
var_div = np.divide(var1, var2)
var_pow = np.power(var1, var2)
var_mod = np.mod(var1, var2)
var_reciprocal = np.reciprocal(var1)
print(var1,"+",var2,"=",var_add)
print(var1,"-",var2,"=",var_sub)
print(var1,"*",var2,"=",var_mul)
print(var1,"/",var2,"=",var_div)
print(var1,"**",var2,"=",var_pow)
print(var1,"%",var2,"=",var_mod)
print(1,"/",var1,"=",var_reciprocal)



[1 2 3 4] + [1 2 3 4] = [2 4 6 8]
[1 2 3 4] - [1 2 3 4] = [0 0 0 0]
[1 2 3 4] * [1 2 3 4] = [ 1  4  9 16]
[1 2 3 4] / [1 2 3 4] = [1. 1. 1. 1.]
[1 2 3 4] ** [1 2 3 4] = [  1   4  27 256]
[1 2 3 4] % [1 2 3 4] = [0 0 0 0]
1 / [1 2 3 4] = [1 0 0 0]


# Arithmetic Operations on Numpy 2D arrays

In [38]:
# By using arithmetic operators
var = np.array([[1,2,3,4],[1,2,3,4]])
var_add = var + 3
print(var)
print(var_add)

[[1 2 3 4]
 [1 2 3 4]]
[[4 5 6 7]
 [4 5 6 7]]


In [40]:
# By using numpy function
var = np.array([[1,2,3,4],[1,2,3,4]])
var_add = np.add(var, 3)
print(var)
print(var_add)

[[1 2 3 4]
 [1 2 3 4]]
[[4 5 6 7]
 [4 5 6 7]]


In [34]:
# By using arithmetic operators
var1 = np.array([[1,2,3,4],[1,2,3,4]])
var2 = np.array([[1,2,3,4],[1,2,3,4]])
var_add = var1 + var2
var_sub = var1 - var2
var_mul = var1 * var2
var_div = var1 / var2
var_pow = var1 ** var2
var_mod = var1 % var2
var_reciprocal = 1 / var1
print(var1,"+",var2,"=",var_add)
print(var1,"-",var2,"=",var_sub)
print(var1,"*",var2,"=",var_mul)
print(var1,"/",var2,"=",var_div)
print(var1,"**",var2,"=",var_pow)
print(var1,"%",var2,"=",var_mod)
print(1,"/",var1,"=",var_reciprocal)



[[1 2 3 4]
 [1 2 3 4]] + [[1 2 3 4]
 [1 2 3 4]] = [[2 4 6 8]
 [2 4 6 8]]
[[1 2 3 4]
 [1 2 3 4]] - [[1 2 3 4]
 [1 2 3 4]] = [[0 0 0 0]
 [0 0 0 0]]
[[1 2 3 4]
 [1 2 3 4]] * [[1 2 3 4]
 [1 2 3 4]] = [[ 1  4  9 16]
 [ 1  4  9 16]]
[[1 2 3 4]
 [1 2 3 4]] / [[1 2 3 4]
 [1 2 3 4]] = [[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[1 2 3 4]
 [1 2 3 4]] ** [[1 2 3 4]
 [1 2 3 4]] = [[  1   4  27 256]
 [  1   4  27 256]]
[[1 2 3 4]
 [1 2 3 4]] % [[1 2 3 4]
 [1 2 3 4]] = [[0 0 0 0]
 [0 0 0 0]]
1 / [[1 2 3 4]
 [1 2 3 4]] = [[1.         0.5        0.33333333 0.25      ]
 [1.         0.5        0.33333333 0.25      ]]


In [36]:
# By using numpy functions
var1 = np.array([[1,2,3,4],[1,2,3,4]])
var2 = np.array([[1,2,3,4],[1,2,3,4]])
var_add = np.add(var1, var2)
var_sub = np.subtract(var1, var2)
var_mul = np.multiply(var1, var2)
var_div = np.divide(var1, var2)
var_pow = np.power(var1, var2)
var_mod = np.mod(var1, var2)
var_reciprocal = np.reciprocal(var1)
print(var1,"+",var2,"=",var_add)
print(var1,"-",var2,"=",var_sub)
print(var1,"*",var2,"=",var_mul)
print(var1,"/",var2,"=",var_div)
print(var1,"**",var2,"=",var_pow)
print(var1,"%",var2,"=",var_mod)
print(1,"/",var1,"=",var_reciprocal)


[[1 2 3 4]
 [1 2 3 4]] + [[1 2 3 4]
 [1 2 3 4]] = [[2 4 6 8]
 [2 4 6 8]]
[[1 2 3 4]
 [1 2 3 4]] - [[1 2 3 4]
 [1 2 3 4]] = [[0 0 0 0]
 [0 0 0 0]]
[[1 2 3 4]
 [1 2 3 4]] * [[1 2 3 4]
 [1 2 3 4]] = [[ 1  4  9 16]
 [ 1  4  9 16]]
[[1 2 3 4]
 [1 2 3 4]] / [[1 2 3 4]
 [1 2 3 4]] = [[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[1 2 3 4]
 [1 2 3 4]] ** [[1 2 3 4]
 [1 2 3 4]] = [[  1   4  27 256]
 [  1   4  27 256]]
[[1 2 3 4]
 [1 2 3 4]] % [[1 2 3 4]
 [1 2 3 4]] = [[0 0 0 0]
 [0 0 0 0]]
1 / [[1 2 3 4]
 [1 2 3 4]] = [[1 0 0 0]
 [1 0 0 0]]
